### ISSUE TITLE
app crashes when opening a file with open with

### ISSUE THREAD

**Issue by csersyadav** [arpitkh96/AmazeFileManager#351]
Hi,
current version crashes while opening a file and it ask application to open with.

it always crashes but still we are able to open that file

**Comment by vishal0071** [comment]
Which version?

**Comment by csersyadav** [comment]
3.1.1

**Comment by vishal0071** [comment]
Sry closed by mistake. Anyways, try latest beta, should fix this issue.

**Comment by csersyadav** [comment]
i will test

**Comment by csersyadav** [comment]
Thanks 
it is fixed in beta 
i tested on beta-2

**Comment by mase76** [comment]
I still have this issue with 3.1.1 on my Fairphone2. The file is opened with the prefered app, but Amaze crashes.
